# Generated by Django 5.1.2 on 2024-10-13 18:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('organisation_slug', models.SlugField(unique=True)),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_email', models.EmailField(max_length=254, unique=True)),
                ('organisation_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
